/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tinnova.bubble_sort;

import com.tinnova.bubble_sort.core.BubbleSort;

public class App {

    public static void main(String[] args) {
        var orderedVector = BubbleSort.order(new Integer[]{5, 3, 2, 4, 7, 1, 0, 6});
        for (int value :
                orderedVector) {
            System.out.print(value + "-");
        }
    }
}
